version: '3.8'

services:
  api-blue:
    image: zero-api-a:${IMAGE_TAG:-latest}
    build: .
    container_name: api-blue-a
    restart: unless-stopped
    environment:
      - ConnectionStrings__DefaultConnection=${DB_URL}
    # Master Nginx가 찾아올 수 있도록 가상머신의 8080 포트를 개방합니다.
    ports:
      - "127.0.0.1:8080:8080" 
    stop_grace_period: 60s

  api-green:
    image: zero-api-a:${IMAGE_TAG:-latest}
    build: .
    container_name: api-green-a
    restart: unless-stopped
    environment:
      - ConnectionStrings__DefaultConnection=${DB_URL}
    # Green은 8081 포트를 개방합니다.
    ports:
      - "127.0.0.1:8081:8080"
    stop_grace_period: 60s  